zshrc: change sudo-command-line switch 'sudo'
grml/grml-etc-core pull request #119
Opened 2021-05-17 14:35 UTC by a-wing

fix add 'sudo' plugin zsh-syntax-highlighting error

If not `sudo`, use `sudo-command-line` add

```sh
ls

# sudo-command-line

sudo ls
```

If has `sudo`, use `sudo-command-line` remove

```
sudo ls

# sudo-command-line

ls 
```

If use zsh plugin `zsh-syntax-highlighting`, run `sudo-command-line` this color error. need `reset-prompt`

2021-05-17 14:59 UTC, mika commented
Thanks for the PR! No objections per sē , but sadly I don't understand / can't parse the commit message. Could you try rewording the explanation in the commit message for the underlying problem? Do you have steps to reproduce the issue for us?

2021-05-17 15:49 UTC, a-wing commented
I Change two code:
1. I added to remove prefix `sudo`
2. fix syntax-highlighting error


Default:

```sh
bindkey | grep sudo
"^Os" sudo-command-line
```

use this hotkey, auto command add/remove prefix `sudo`

* * *

syntax-highlighting error

<img width="220" alt="Screen Shot 2021-05-17 at 23 30 08" src="https://user-images.githubusercontent.com/18189138/118517508-d8b32400-b769-11eb-8b0c-8832a728ce3a.png">

The `reset-prompt` fix this problem. But this is related to the use of themes and plugins

2021-05-17 17:10 UTC, ft requested changes

2021-05-17 17:10 UTC, ft commented on etc/zsh/zshrc
> +    if [[ ${BUFFER:0:${#cmd}} == ${cmd} ]]; then
This looks like a less readable version of  `if [[ $BUFFER == ${cmd}* ]]; then`. I'd prefer the more readable approach.

The `${param:...:...}` indexing syntax is a fairly new addition in zsh. So using the other approach makes the code more portable across zsh versions.

2021-05-17 17:10 UTC, ft commented on etc/zsh/zshrc
> +        BUFFER="${BUFFER:${#cmd}}"
So, this is a new feature, with this, you can toggle whether or not `$BUFFER` has a `sudo` prefix. That's the intention?

I like that.

But again, the indexing mechanism used can be changed to something that's more portable across zsh versions: `BUFFER="${BUFFER#$cmd}"`. So I'd prefer that.

2021-05-17 17:10 UTC, ft commented on etc/zsh/zshrc
> +    zle reset-prompt
This is for fixing the zsh-syntax-highlight issue, right?

Normally, I would say that there's a problem in zsh-syntax-highlight, because it's its job to correctly put up colour if a widget changes the context if the line-editor's buffer. On the other hand, the impact in negligible and it would work around a problem in exiting zsh-syntax-highlight installations.

Soooo, I suppose we can allow this.

2021-05-17 17:11 UTC, ft commented
I do like the use of `${#cmd}` instead of a magic number like `5`. :)

2021-05-18 03:09 UTC, a-wing commented on etc/zsh/zshrc
> +    if [[ ${BUFFER:0:${#cmd}} == ${cmd} ]]; then
This might be better

2021-05-18 03:11 UTC, a-wing commented
Remove use indexing syntax

2021-05-18 18:39 UTC, ft commented
This new version of the code look good to me! Thanks!

2021-05-18 18:42 UTC, ft approved these changes

2021-05-19 05:22 UTC, merged

2021-05-19 05:22 UTC, mika commented
Thanks a lot @a-wing for this PR! Thanks @ft for your feedback and review!
:tada: