tmux: status-right: Show IP addresses (similar to our GNU/screen configuration
grml/grml-etc-core pull request #159
Opened 2024-10-07 11:30 UTC by jkirk

2024-10-08 09:51 UTC, moviuro commented on etc/tmux.conf
> +set -g status-right "#[fg=green](net: #(hostname -I | sed -e 's/ [^ ]*:.*$//;s/ / | /g;s/ | $//')) #[fg=yellow]%Y-%m-%d %H:%M"
FWIW, `hostname -I` is not portable to e.g. OpenBSD: https://man.openbsd.org/hostname.1

2024-10-08 09:58 UTC, mika commented on etc/tmux.conf
> +set -g status-right "#[fg=green](net: #(hostname -I | sed -e 's/ [^ ]*:.*$//;s/ / | /g;s/ | $//')) #[fg=yellow]%Y-%m-%d %H:%M"
> FWIW, `hostname -I` is not portable to e.g. OpenBSD: https://man.openbsd.org/hostname.1

Excellent point, thanks @moviuro! I think we should go through our wrapper script then, which only runs `hostname -I` if that's available? (And possibly fall back to something else otherwise, if at all?)

2024-10-08 10:34 UTC, zeha commented on etc/tmux.conf
> +set -g status-right "#[fg=green](net: #(hostname -I | sed -e 's/ [^ ]*:.*$//;s/ / | /g;s/ | $//')) #[fg=yellow]%Y-%m-%d %H:%M"
if we do wrapper scripts we can stick to the perl variant

2024-10-08 10:34 UTC, zeha commented on etc/tmux.conf
> +set -g status-right "#[fg=green](net: #(hostname -I | sed -e 's/ [^ ]*:.*$//;s/ / | /g;s/ | $//')) #[fg=yellow]%Y-%m-%d %H:%M"
(its not like ip-screen worked on openbsd either)

2024-10-08 10:36 UTC, mika commented on etc/tmux.conf
> +set -g status-right "#[fg=green](net: #(hostname -I | sed -e 's/ [^ ]*:.*$//;s/ / | /g;s/ | $//')) #[fg=yellow]%Y-%m-%d %H:%M"
> if we do wrapper scripts we can stick to the perl variant

wondering whether it would make sense to have `ip-screen` inside $PATH which then is simple script to check for `hostname -I` support and if not supported falls back to your perl script otherwise? :grin:

2024-10-08 11:13 UTC, zeha commented on etc/tmux.conf
> +set -g status-right "#[fg=green](net: #(hostname -I | sed -e 's/ [^ ]*:.*$//;s/ / | /g;s/ | $//')) #[fg=yellow]%Y-%m-%d %H:%M"
Maybe it's worth having separate config file sets, one to use on the live CD, and one for people pulling the individual files. Not sure how f.e. screenrc worked before for individual-config-file users?

2024-11-20 15:33 UTC, zeha requested changes
@jkirk will come with a _generic version etc

2025-02-18 19:12 UTC, jkirk commented on etc/tmux.conf
> +set -g status-right "#[fg=green](net: #(hostname -I | sed -e 's/ [^ ]*:.*$//;s/ / | /g;s/ | $//')) #[fg=yellow]%Y-%m-%d %H:%M"
I played around with a "if-shell" line to check if `hostname` exists. I'll update this PR.

2025-02-18 19:15 UTC, jkirk commented on etc/tmux.conf
> +set -g status-right "#[fg=green](net: #(hostname -I | sed -e 's/ [^ ]*:.*$//;s/ / | /g;s/ | $//')) #[fg=yellow]%Y-%m-%d %H:%M"
Argl, we are talking about `hostname -I`.

Can we have a decision on this? Keep this `hostname -I` line, implement a wrapper script (again) or drop this PR?

2025-02-18 19:44 UTC, jkirk commented on etc/tmux.conf
> +set -g status-right "#[fg=green](net: #(hostname -I | sed -e 's/ [^ ]*:.*$//;s/ / | /g;s/ | $//')) #[fg=yellow]%Y-%m-%d %H:%M"
FWIW, I came up with a `hostname -I` command line option check. Please (re)review.

2025-02-24 08:17 UTC, mika approved these changes
Untested, LGTM

2025-02-24 08:19 UTC, zeha commented on etc/tmux.conf
> +set -g status-right-length 100
what exactly does this change and is this a good idea on 80x25 screens?

2025-02-24 08:51 UTC, jkirk commented on etc/tmux.conf
> +set -g status-right-length 100
Hmm. Good question. It was previously set to 16 which was too short, I set it arbitrary to 100.

I just checked to man page, the default is 40, which should be fine for at least one IP:
```
❯ echo "(net: 192.168.123.254) 2025-02-24 09:43" | wc -c
40
```

FTR, my right status line (`(net: 10.17.0.209 | 10.10.2.100 | 10.17.0.128) 2025-02-24 09:48`) is also shown fine without setting ` status-right-length`. I'll drop it the line in the PR.

2025-02-24 09:00 UTC, jkirk commented on etc/tmux.conf
> +set -g status-right-length 100
Updated the PR. Thx!

2025-02-24 09:14 UTC, mika approved these changes

2025-02-24 09:29 UTC, merged